---
netunicorn.connector.salt.public_grains:
  - location
  - osarch
  - kernel

netunicorn.connector.salt.endpoint: "https://infra.example.com/saltapi"
netunicorn.connector.salt.login: "username"
netunicorn.connector.salt.password: "password"
netunicorn.connector.salt.eauth: "pam"



