---
netunicorn.connector.salt.public_grains:
  - location
  - osarch
  - kernel

netunicorn.connector.salt.endpoint: "https://infra.example.com/saltapi"
netunicorn.connector.salt.username: "username"
netunicorn.connector.salt.password: "password"
netunicorn.connector.salt.eauth: "pam"
netunicorn.connector.salt.node_cache_timeout_minutes: 10
